---

- name: "Creating sudoers configuration in /etc/sudoers.d/{{ sudo_sudoers_file }}"
  template:
    src: "etc/sudoers.d/ansible.j2"
    dest: "/etc/sudoers.d/{{ sudo_sudoers_file }}"
    validate: "visudo -cf %s"
    owner: root
    group: "{{ sudo_sudoers_group }}"
    mode: "0440"
